### ISSUE TITLE
Feature request: Automatically hide icon in KDE

### ISSUE THREAD

**Issue by protist** [foudfou/FireTray#137]
In KDE's tray, users have the ability to set icons' visibility to `Hidden`, `Always visible` or `Auto`. In the last case, the icons only show when necessary. For example, the battery icon is hidden when 100%, and shown when < 100%; the usb and printer icons are hidden unless something is connected or printing respectively.

It'd be great if there were an option to make FireTray do something similar, only showing when there are unread messages. I think this can be attained by using KDE's StatusNotifierItem interface, although I'm not sure if there are alternative ways.

**Comment by foudfou** [comment]
Can you try 59320d5  ? [xpi here](https://cloud.foudil.fr/public.php?service=files&t=bce70855267e411f8a4e8c476d52ec29)

**Comment by protist** [comment]
Yes! That works well for me, although I ran into the "wrong unread message count" issue while testing. (I assume that's just Thunderbird's fault though.) Thanks for the implementation!

However, I noticed that when the icon hides, it is no longer available in the notification popup menu. For example, see this screenshot: https://i.imgur.com/jKMEyQw.png

Here, you can see (e.g.) "Manage Print Jobs" is hidden when not in use, but still accessible via the popup. Instead, FireTray appears to make the icon totally disappear. I'm not sure if this is the expected behaviour, and is certainly no big deal (I never use the contextual menu anyway).

**Comment by foudfou** [comment]
Oops, we need the icon when windows are hidden. I'll fix that.

**Comment by Zranz** [comment]
In Unity it doesn't work as I think you intended... I do not have unread emails, but I still see the icon when Thunderbird is minimized with the option "Show tray icon only if a windows is hidden" **off**, and "Hide icon when no mail" is **on**.

But as Rabotyahoff commented in [ #150](https://github.com/foudfou/FireTray/issues/150), another icon in Unity is an excess, as Thunderbird is already integrated in the notifications tab. The useful features for us are the autoclose option on startup and on close, as icon is already provided with Thunderbird (as well as notifications, and change of color of the icon with unread email)

![two_icons](https://cloud.githubusercontent.com/assets/10563919/6208011/2b4fd0da-b5b1-11e4-9b88-5abcaa6fcbd2.png)

**Comment by foudfou** [comment]
@protist @Zranz, I made both prefs exclusive, as I think they interfere with each other. Is that better for you (see f89009dace) ?

**Comment by protist** [comment]
@foudfou For me, using KDE, the prefs were never an issue, since I would always have the window visible, and always want the icon "displayed" (letting KDE's panel do the hiding). I presume that this commit doesn't change that. I haven't installed it, but I'm happy to if you like, if there an xpi?

**Comment by Zranz** [comment]
@foudfou I agree prefs being mutually exclusive is probably correct. 
My intended use would still be to have a third option which is to completely disable the icon, regardless of window being active, or unread email.

**Comment by foudfou** [comment]
@Zranz could you open another issue for this ? I think there are already requests for this or something similar. If so, could you cite this current issue overthere ?
