### ISSUE TITLE
0.5.3: systray icon invisible at KDE 4.14.3 at a  64 bit hardened Gentoo Linux

### ISSUE THREAD

**Issue by toralf** [foudfou/FireTray#138]
the icon is there -but invisible

**Comment by Demontager** [comment]
Downgraded to 0.5.3, because of no unread messages count icon shown, which was very useful. Also instead of thunderbird icon it apears some kind of star (0.5.4).

**Comment by foudfou** [comment]
@Demontager your problem looks like #147.

**Comment by Demontager** [comment]
Yeah, thanks! I fixed as @jombra posted.

**Comment by foudfou** [comment]
@toralf this looks like an environment-specific issue. It will be hard for me to test without a similar environment (virtual machine). So, as you overcame the issue, I'm tempted to close it as INVALID or WONTFIX, and let other Gentoo users re-open it it pops up again. Agreed ?

**Comment by toralf** [comment]
ok
