### ISSUE TITLE
FireTray 0.5.4 contextmenu "New Window" shows error page

### ISSUE THREAD

**Issue by informatorius** [foudfou/FireTray#149]
When i click FireTray 0.5.4 contextmenu "New Window"
then a new firefox window is opened 
but goes to url "chrome://browser/content/www.google.de"
which shows an error page "Error: File not found".
Expected behavior: Show start page "www.google.de"
Did work correctly in FireTray 0.5.3
(Firefox 34 on Windows 7)

**Comment by foudfou** [comment]
Thanks for reporting.
This happens when the homepage is not defined as a proper URL (ex: www.google.de instead of http://www.google.de).
Can you try 3316aee ? [Xpi here](https://cloud.foudil.fr/public.php?service=files&t=9ff26d59c6204da8cf76b62f2afc59a8).

**Comment by informatorius** [comment]
I tried, it is fixed.
