### ISSUE TITLE
How to disable tray icon?? 

### ISSUE THREAD

**Issue by WeeHool** [foudfou/FireTray#150]
Hi.
I need tip, how to disable tray icon of Firetray permanently, not only, when visible Thunderbird.
Thank you.

**Comment by foudfou** [comment]
Hi, I'm not sure to understand: how about uninstalling FireTray ?

**Comment by WeeHool** [comment]
Not. I am on Linux Ubuntu and show me new message in global menu. I have firetray only for stay hide open Thunderbird. After upgrade to 0.5.4 show icon in tray. Unnecessary for me.
Sorry for me english.

**Comment by Rabotyahoff** [comment]
After upgrade to 0.5.4 icon always shows in system tray. But in Ubuntu unity Thunderbird integrated with indicator-messages. We need to hide firetray icon.
![tray1](https://cloud.githubusercontent.com/assets/1113031/5613474/7aa826f8-94ed-11e4-83fe-ab3717193fdd.png)

**Comment by foudfou** [comment]
How about the *Show tray icon only if a window is hidden* preference ?

**Comment by Rabotyahoff** [comment]
No. Thunderbird works fine on ubuntu with standart indicator-messages. And all additional icons in tray are excess.

**Comment by foudfou** [comment]
Is this similar to #137 ?

**Comment by jelhan** [comment]
Perhaps FireTray is wrong addon for this use case? I had the same issue and therefor switched to [MinimizeToTray revisted](https://addons.mozilla.org/en-US/thunderbird/addon/minimizetotray-revived/)

**Comment by Rabotyahoff** [comment]
I think #150 similar to #137.

MinimizeToTray can't minimize window on close.

**Comment by jelhan** [comment]
I'm not sure if [MinimizeToTray](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray/) can, but [MinimizeToTray revisited](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray-revived/) can minimize window on close. There are settings in *MinimizeToTray revistied* which controll if windows should be minimized to tray on close, on minimze, on both or never. I've german version installed otherwise I would attach an screenshot of settings.

**Comment by Rabotyahoff** [comment]
jelhan thank you. It works fine!

**Comment by Zranz** [comment]
FireTray has more options than [MinimizeToTray revisited](https://addons.mozilla.org/de/thunderbird/addon/minimizetotray-revived/). For instance "Start application hidden on tray" which I find incredibly useful.

So adding an option to disable the icon would be great, in particular for Ubuntu users.

**Comment by hieinji** [comment]
I agree with Zranz.

2015-01-16 17:35 GMT+01:00 Zranz <notifications@github.com>:

**Comment by foudfou** [comment]
Closing this one as duplicate of #137. See [this fix](/foudfou/FireTray/issues/137#issuecomment-74439361). Can you provide feedback there ?

**Comment by Mrfuyu** [comment]
To always hide the tray icon you can select the user defined icon under 'symbol' and leave the field empty.

**Comment by zranz** [comment]
Your suggested fix does not work. After sending thunderbird to the tray, default icon reappears.

**Comment by Mrfuyu** [comment]
With Xfce it works. Unity behaves different seemingly.
