### ISSUE TITLE
Firetray broke on firefox 35 on KDE Plasma 5

### ISSUE THREAD

**Issue by anexation** [foudfou/FireTray#157]
Firetray broke on firefox 35 on KDE Plasma 5

**Comment by foudfou** [comment]
Hi thanks for reporting. Do you know where I can find a virtual image (ex. VirtualBox) for testing ?

**Comment by Karmaki** [comment]
I confirm that Firetray is broken for the last Firefox update (35.0) on Xubuntu 14.04.1.
It is working for Thunderbird (31.3.0) though.

**Comment by anexation** [comment]
foudou, you can use my iso just need to update firefox, "sudo pacman -Sy firefox-kde"

https://sourceforge.net/projects/manjarotest/files/0.9.0/kf5-plasma-dev/0111-OLD/

im working on packages now for this release to be based off all stable Plasma  5 packages so marked it as old.

**Comment by jensberke** [comment]
Don't know if that's relevant for this issue, but I get the following output when starting Firefox from the shell (Xubuntu 14.10, Firefox 35.0):

JavaScript error: resource://firetray/linux/FiretrayAppIndicator.jsm, line 71: TypeError: redeclaration of variable pref

**Comment by jensberke** [comment]
Some additional infos to my previous post: I don't use KDE, but XFCE. FireTray completely stopped working after updating Firefox from 34 to 35. No tray icon at all, neither default nor custom. Firefox quits when clicking the window close button.

**Comment by jensberke** [comment]
...and some more shell output when I quit Firefox:
18:55:30.419 ERROR firetray.FiretrayWindow unknown window while lookup
18:55:30.420 ERROR firetray.Window can't unregister unknown window null

**Comment by peterruhnau** [comment]
On xubuntu 14.04.1: Setting extensions.firetray.with_appindicator to false (in about:config) fixes this.

**Comment by Karmaki** [comment]
Thanks @peterruhnau: it worked for me too.

**Comment by cyberbeat** [comment]
The code for using appindicator did not work for me on plasma 5, I looked at the code, and understood, why:

a shell command "plasma-desktop -v" is executed to get plasma version.

problem: this works only for kde-4, in plasma-5 session, there is command "plasma-desktop" anymore, but

> plasmashell -v

which results in

plasmashell 5.2.0

for me. Please adapt your script.

What also does not work (could be another bug report):
- toggle thunderbird window via left-mouse button.
- toggling window via middle-click works, but the window is not focussed, it only appears in the taskbar when toggle is on.

**Comment by foudfou** [comment]
@cyberbeat thx for investigating.
Do you know any reliable command that would work across all plasma versions (`kwin`, `kstart`, `kdepasswd`, `kdeopen`, ...) ?
The issues you mentioned are known (#130) and might be addressed by #143.

**Comment by cyberbeat** [comment]
I think the current method is ok, plasma-desktop for kde-4 and plasmashell for kde-5.

a few links to the topic:

https://launchpad.net/sni-qt

http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

http://agateau.com/2011/statusnotifieritem-for-qt-applications/

**Comment by foudfou** [comment]
@cyberbeat I don't have any KDE5 environment at hand. Couldn't find how to get plasma's version with dbus. Meanwhile, can you tell me if `kde-open` is available in KDE5 ?

**Comment by foudfou** [comment]
@cyberbeat got it: KDE_SESSION_VERSION is sufficient (b792bb86a6).
Can you build and confirm ?

**Comment by cyberbeat** [comment]
for me the environment variable is set:
>echo $KDE_SESSION_VERSION
>5

seems to be a good and more reliable way to test the desktop-session than existance/output of programs.

I am on opensuse with plasma-5 with a mix of plasma-5 desktop and kde-4 applications.

And there are
kde-open (kde4) and kde-open5 (kde5)

**Comment by foudfou** [comment]
See also #130. I'll close this one as it seems resolved. Feel free to reopen.
