### ISSUE TITLE
Doesn't unhide the icon for new mail notification in Thunderbird (Windows 7)

### ISSUE THREAD

**Issue by chang-zhao** [foudfou/FireTray#159]
Normally, I use MinTrayR and keep Thunderbird icon hidden ("Only show notifications"), so that a new mail causes another icon to appear ("envelope").
When using FireTray instead, it transforms the default icon, so the icon showing new mails remains hidden.

**Comment by foudfou** [comment]
Right: as explained in the README, `mail.biff.show_tray_icon` is unset during the session by FireTray. This is because FireTray intends to replace the default biff icon.
Now, can your request be rephrased as: having the icon shown only for new/unread messages ?

**Comment by foudfou** [comment]
Duplicate of #137 #150 ?

**Comment by chang-zhao** [comment]
It's similar to #137, yes. In Windows + MinTrayR, ThunderBird has 2 Icons:
- the main icon can be set as hidden.
- the second icon appears when a message arrives. That second icon can be set as visible.
Another solution could be as in #137, but in Windows, without KDE, to make icon visible only when new messages are there.

**Comment by foudfou** [comment]
Can you try 59320d5 ? [xpi here](https://cloud.foudil.fr/public.php?service=files&t=bce70855267e411f8a4e8c476d52ec29)

**Comment by foudfou** [comment]
Well, I'll just close this one as a duplicate and follow up in  #137.
