### ISSUE TITLE
The tray icon in KDE 4.13.3 (Kubuntu 14.04.1) doesn't respond to the mouse actions as before.

### ISSUE THREAD

**Issue by negora** [foudfou/FireTray#161]
Hello:

This report is about the behaviour of both the left mouse button and the mouse wheel. On the one hand, with previous versions of FireTray, I could do a single-click on the tray icon and Thunderbird was shown again. But after the last update of FireTray, it doesn't work any more. I've to use the contextual menu or the middle mouse button (the wheel button), which is less comfortable.

On the other hand, I've tried to use the spin of the mouse wheel to hide and show the window. I've put the pointer over the tray icon, but it hasn't responded to my actions. It hasn't mattered whether I've configured it to show the window while spinning the mouse wheel backwards or the opposite.

To make sure that my configuration wasn't affecting the results, I've backed up my Thunderbird profile and have started with a new one. The results have been the same.

Thank you.

**Comment by haridas** [comment]
I'm also facing the same issue. I could open the Thunderbird by doing single click on the tray icon. But now the tray icon is not responding to the single click. What I'm doing is, I do right click on that Icon and then click on the open section menu on the popup. This behavior giving me trouble while using other items on my system Tray. 

I'm on Kubuntu 14.10 and KDE - 4.13.3

I'm trying to see, is this issue of the KDE panel or the FireTray causing the issue ?

**Comment by haridas** [comment]
Now it works for me.. I cloned the repo and build the extension myself by running `make build`. Then removed the existing one I downloaded from the repo and loaded the compiled one. Now it's working. 

Don't know the exact reason of why it's not working, but looks like some compatibility issue.

**Comment by foudfou** [comment]
Hi,
The current version of FireTray uses libappindicator when appropriate (#130).
Problem is: FireTray can't determine what *appropriate* is exactly. This is being fixed (#157 for instance).
@negora the solution for plasma4 is to downgrade FireTray, or build the latest version as @haridas did (see wiki for instructions).
FireTray won't *fully* work with plasma5 until #143 is fixed.
Now I'm closing this one, as these subjects are already discussed in other tickets.
Cheers

**Comment by negora** [comment]
Thank you! I'll build the latest version ;) .
