### ISSUE TITLE
When libappindicator is installed, TB freezes on resume

### ISSUE THREAD

**Issue by RalfJung** [foudfou/FireTray#177]
When the libappindicator3 library is installed and this plugin is enabled, Thunderbird freezes when the machine comes back from a suspend-resume cycle. This is reproducible.

Note that libappindicator3 is not actually used, I disabled it by setting `extensions.firetray.with_appindicator` to false. The mere existence of the library suffices to trigger the problem.

**Comment by RalfJung** [comment]
Oh, I forgot to mention: This is both with v0.5.4 and a627772.

**Comment by 8hoek** [comment]
Using Linux Mint 17.2 and Thunderbird 38.3.0. Version Firetray 0.5.6.1 makes TB crash after suspend.
Installed older version 0.5.3.1 problem of crashing TB after suspend solved.

**Comment by RalfJung** [comment]
I am now using development version 998e6b8253a73a5417a28c5364508d03f586f656for quite some time without any freezing issues.

**Comment by 8hoek** [comment]
Installed Firetray 0.6.0. Does work flawlessly in Linux mint 17.2 cinnamon TB 38.3.0

**Comment by foudfou** [comment]
Assuming v0.6.0 fixes the issue.
