### ISSUE TITLE
FireTray uses obsoleted system tray icons in KDE Plasma 5

### ISSUE THREAD

**Issue by Temlakos** [foudfou/FireTray#181]
FireTray 0.5.6 uses the XAppend protocol for generating system tray icons. With the advent of Plasma 5 in KDE, XAppend support has vanished. Your system-tray icons therefore do not appear, and minimizing to the tray causes the application to disappear completely.

My current remedy is to install wmsystemtray and run that with no decoration and a white background.

See here:

http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

for details and instructions for developers.

**Comment by foudfou** [comment]
Hi, see #130, and all subsequent issues.
