### ISSUE TITLE
include/exclude custom folders to/from messages count

### ISSUE THREAD

**Issue by Myppomeu** [foudfou/FireTray#183]
Hello!
I have created some folder in my mail. It would be wonderful if I can choose which folder to display in tray when new mail arrives and which not to display.

**Comment by foudfou** [comment]
Hi, the *Only favorite folders* option is a mean to select which folder to include in the count. Folders can be made favorite by right-clicking on the folder, and selecting *Favorite Folder*.
I'll close this issue, but feel free to re-open if I misunderstood.
