### ISSUE TITLE
Makefile check_loglevel fails (loglevel was changed from Warn to All, but makefile was not updated)

### ISSUE THREAD

**Issue by neoh4x0r** [foudfou/FireTray#198]
Commit 6e628dfbff591b62209a4ed12645f56598783d3e
modified src/modules/logging.jsm and changed the logging level from Warn to All

But the Makefile has not been updated since commit: 1c76f1c1f94681af1ca5421cd140cef224fb57e5
to reflect the change.
check_loglevel:
	@echo "checking loglevel"
	@[ "Warn" = "$(FIRETRAY_LOG_LEVEL)" ]

this last line should read
	@[ "All" = "$(FIRETRAY_LOG_LEVEL)" ]

**Comment by foudfou** [comment]
Yeah you're right. `FIRETRAY_LOG_LEVEL` should be `Warn` to limit output for regular use. This is fixed in branch `gtk3` and will be merged soon. Thx for noticing!
