### ISSUE TITLE
KDE plasma 5 missing icons

### ISSUE THREAD

**Issue by foudfou** [foudfou/FireTray#199]
As reported by @kF13Ld in [#130](/foudfou/FireTray/issues/130#issuecomment-138086675), the icon does not show, but it is there. I.e. I can right click on it to get the context menu, and middle click to open the thunderbird window.

![thunderbird_firetray_no_icon](https://cloud.githubusercontent.com/assets/13854565/9704661/9b3dc3ec-54ae-11e5-8e6f-a6ab344bc98f.png)

Also, for new messages, a letter symbol correctly appears. But for some reasons, the normal thunderbird icon is invisible. I have already tried setting a custom icon, with no help.

**Comment by foudfou** [comment]
@kF13Ld, did you install through your distribution or through  some tarball downloaded from Mozilla ?

**Comment by kF13Ld** [comment]
If you mean thunderbird, I just installed the Ubuntu package via `apt-get install thunderbird`. I have version 38.2.0 installed.

**Comment by foudfou** [comment]
I could reproduce it by installing from Mozilla => icon(s?) not installed to the standard directory.
Could you give a try at 70335fa7ac ?

**Comment by kF13Ld** [comment]
Hmm, I uninstalled Firetray from thunderbird, did a new `git clone`, build and installed it in thunderbird.

Now, I don't see an icon at all (not even for new messages). Also, there doesn't seem to be a hidden icon anymore.

The error console says (directly after startup):
`ERROR firetray.StatusIcon Missing libappindicator for gtk2
resource://gre/modules/Log.jsm
line: 749`
Don't know if that is a new message or not.

**Comment by foudfou** [comment]
@kF13Ld right: you need to install libappindicator for gtk2.

**Comment by kF13Ld** [comment]
Ok, I already had the package `libappindicator3-1` installed, but I also needed `libappindicator1` for it to work. Now I see the thunderbird icon which is a step forward ;-)
But it is of a rather bad quality:
![thunderbird_firetray_no_icon_bad_quality](https://cloud.githubusercontent.com/assets/13854565/9743627/a506d732-5667-11e5-9deb-28a6ac1f3df3.png)

When trying to setup a custom icon (a *.png file) in the FireTray settings, the icon stays the same. I.e. the setting has no effect.

**Comment by foudfou** [comment]
@kF13Ld right: while fixing this current issue, I found out setting custom icons is currently broken :( And I'm currently working on it. I'll open a dedicated issue if it's not resolved quickly.
I'll close this one as it looks resolved. Feel free to reopen if I'm wrong.

**Comment by foudfou** [comment]
See #200
