### ISSUE TITLE
Please add to firetray Thunderbird Calendar (lightning)

### ISSUE THREAD

**Issue by mateusz2238** [foudfou/FireTray#202]
Please add to firetray Thunderbird Calendar (lightning)

**Comment by foudfou** [comment]
Hi. If what you mean is having the icon react on Lightning events like reminders, then the answer is sorry but no. There is way too much to do with already existing functionality.
Or did you mean something else ?

**Comment by mateusz2238** [comment]
No Thank you

**Comment by foudfou** [comment]
Besides, Lightning already provides nice notifications.
