### ISSUE TITLE
error during initialization

### ISSUE THREAD

**Issue by malan-pl** [foudfou/FireTray#208]
Linux Mint 17.2 Xfce 64-bit
Thunderbird 38.3.0
FireTray 0.5.6.1

"Error: NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]
Source File: resource://firetray/FiretrayHandler.jsm
Line: 510"

System tray icon is visible, but it doesn't restore/hide window. Commenting out line 153 solves the problem:
<code>//this.disablePrefsTmp();</code>

**Comment by BigEd01** [comment]
Same as above but using ubuntu 14.04 Xfce 64-bit
Just updated to 38.3.0 and the app stopped responding  and locking up thunderbird. Tray Icon was visable  but no response. Had to cold kill TB. Remarked out the above line 153 also and looks to be back and running so far.

**Comment by negora** [comment]
I've exactly the same problem on Kubuntu 14.04.3 LTS 64-bit. Some times Thunderbird locks up during the start, but other times it locks up after some time of use. It stops responding and the only way to close it is killing the process with a KILL signal.

I still haven't tested the workaround mentioned by malan-pl.

**Comment by negora** [comment]
Hi again:

I've run Thunderbird from the command line and, every time that it has locked up, it has outputted the following messages:

  (thunderbird:12774): GLib-GObject-WARNING **: cannot register existing type 'GdkKeymap'
  (thunderbird:12774): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
  (thunderbird:12774): Gdk-CRITICAL **: gdk_keymap_have_bidi_layouts: assertion 'GDK_IS_KEYMAP (keymap)' failed

I don't know it it's related with the problem that we're talking about, but just in case, I've preferred to comment it.

**Comment by foudfou** [comment]
Hi, this problem should be resolved in [v0.6.0](https://addons.mozilla.org/en-US/firefox/addon/firetray/versions/0.6.0).

**Comment by malan-pl** [comment]
It seems that the problem has been resolved in the latest version (v0.6.0).
