### ISSUE TITLE
Firetray Causing Thunderbird 38.3.0 to Freeze on Ubuntu

### ISSUE THREAD

**Issue by zauberparacelsus** [foudfou/FireTray#212]
About a week ago, the Ubuntu repositories were updated with Thunderbird 38.3.0.  Since this update, I have found that Thunderbird has been freezing/deadlocking after running for a while.  Usually this happens after resuming from Suspend or after logging in after the screensaver was running.

After researching the issue, I found that the solution to this problem is disabling Firetray.

Source: http://askubuntu.com/questions/683021/thunderbird-freezes-after-updated-to-38-3-0

**Comment by foudfou** [comment]
Hi, I think this has merely been resolved in [v0.6.0](https://addons.mozilla.org/fr/firefox/addon/firetray/versions/0.6.0). If this doesn't work straight away, check the JS-Console (Ctrl-Shift-J) for missing dependencies errors. You might also be missing libappindicator.
Tell us how it goes.
See also #185.

**Comment by 8hoek** [comment]
Installed Firetray 0.6.0 in Linux mint 17.2 Cinnamon. Works flawlessly in TB 38.3.0. No freezing of TB any more after suspend.

**Comment by zauberparacelsus** [comment]
@foudfou Installing v0.6.0 has fixed my issue, thanks!

**Comment by foudfou** [comment]
Cool! Closing then.
