### ISSUE TITLE
Thunderbird segfault on start with FireTray enabled

### ISSUE THREAD

**Issue by positroni** [foudfou/FireTray#233]
Hi, I am on archlinux. After release update to thunderbird 45.7.1-2 I get segfault on start only if FireTray is enabled. If I disable it then it works fine.
The errors that I get if I start thunderbird from terminal are:

`(thunderbird:6581): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'`

`(thunderbird:6581): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed`

`(thunderbird:6581): Gdk-CRITICAL **: IA__gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed`
`Segmentation fault (core dumped)`

**Comment by petrskovoroda** [comment]
Same here. Works perfectly with thunderbird-45.7.1-1

**Comment by positroni** [comment]
Yes unfortunately the project is discontinued.
Even more unfortunate is the fact that this is the only addon I have found that shows the number of new emails arrived.

**Comment by petrskovoroda** [comment]
Not a bug.
Fixed in thunderbird-45.7.1-3

**Comment by positroni** [comment]
Wow what a luck. Thanks for having written it.
