### ISSUE TITLE
Can I add Japanese to this add-on language?

### ISSUE THREAD

**Issue by Shitennouji** [foudfou/FireTray#245]
Thank you for this modified version (FireTray).
It works as expected.
I am very happy that it became available.

by the way,
This add-on is currently in English only, can you add "Japanese"?
If possible, I will cooperate in translating into Japanese.

**Comment by kilobyte** [comment]
Not just English — I see bg, de, en, es, fr, hr, it, nl, pl, ru, sk, uk, zh-CN and zh-TW.  It's trivial to add a new language — all you'd need to do is to provide the texts themselves.  That'd be much appreciated.

On the other hand, there's a problem: this repository is dead, and the official extension receives no updates.  There are active forks, and you'd need to find out which one is most alive these days.

**Comment by Shitennouji** [comment]
I was careless.
I intended to contribute to "Ximi 1970 / FireTray".
I will post again in the correct repository.
https://github.com/Ximi1970/FireTray/issues
Thank you for pointing out.
